name: Build and Deploy (Production)
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 📦
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 🔧
        run: npm ci --include=dev

      - name: Build code 🚚
        run: npm run build

      - name: Release front-end 🎢
        run: |
          sed -i -e 's/%COMMIT_SHA%/'"${GITHUB_SHA::7}"'/g' packages/ide/src/app/tab-start/tab-start.component.html
          export DATE_NOW_FORMATTED=$(date +'%d/%m/%Y %I:%M:%S %p %Z')
          sed -i -e 's*%DATE%*'"${DATE_NOW_FORMATTED}"'*g' packages/ide/src/app/tab-start/tab-start.component.html
          sed -i -e 's/%SENTRY_RELEASE%/'"${GITHUB_SHA}"'/g' packages/ide/src/main.ts
          ./packages/ide/cleanup-icons.sh
          npm run release

      - name: Setup Firebase Hosting 🔥
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_HOSTING_SITE: ${{ vars.FIREBASE_HOSTING_SITE }}
        run: |
          jq -n --arg default "$FIREBASE_PROJECT_ID" '{ "projects": { "default": $default } }' > .firebaserc
          cat <<EOF | tee firebase.json
          {
            "hosting": {
              "site": "$FIREBASE_HOSTING_SITE",
              "public": "packages/ide/dist/browser",
              "headers": [
                {
                  "source": "/**",
                  "headers": [
                    {
                      "key": "Cache-Control",
                      "value": "max-age=900, stale-while-revalidate=180"
                    }
                  ]
                },
                {
                  "source": "**/*.@(jpg|jpeg|gif|png|svg|webp|js|css|eot|otf|ttf|ttc|woff|woff2|font.css)",
                  "headers": [
                    {
                      "key": "Cache-Control",
                      "value": "max-age=604800"
                    }
                  ]
                },
                {
                  "source": "**/portugol-worker/worker.js",
                  "headers": [
                    {
                      "key": "Cache-Control",
                      "value": "max-age=900, stale-while-revalidate=180"
                    }
                  ]
                }
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }
          EOF

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
          channelId: live

      - name: Create Sentry release 📦
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: packages/ide/dist/browser
